# Generated by Django 6.0.6 on 2026-06-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("JEFE", "Jefe"),
                            ("EMPLEADO", "Empleado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("usuario", models.CharField(max_length=50, unique=True)),
                ("contraseña", models.CharField(max_length=100)),
            ],
        ),
    ]
